language: python
python:
  - "2.7"
  - "2.6"
  - "2.5"
  - "3.2"
install:
  - if [ $TRAVIS_PYTHON_VERSION == '2.5' ]; then pip install -r python25-requirements.txt --use-mirrors; fi
  - if [ $TRAVIS_PYTHON_VERSION == '2.6' ]; then pip install -r python26-requirements.txt --use-mirrors; fi
  - python setup.py install
script:
  - cd # Run installed code (maybe 2to3ed), not code in current directory (always for python2)
  - python -m github.tests
